---

- block:
    - include_tasks: pgdg_check.yml
      with_items: "{{ postgresql_versions }}"
      loop_control:
        loop_var: pgdg_version
    
    - name: "postgresql - pgdg - install pgdg {{ postgresql_versions | join(', ') }}"
      include_tasks: pgdg_repo_item.yml
      with_items: "{{ postgresql_versions }}"
      loop_control:
        loop_var: pgdg_version
      when: ansible_os_family == 'RedHat'
    
    - import_tasks: pgdg_debian.yml
      when: ansible_os_family == 'Debian'
    
    - name: "postgresql - install {{ postgresql_versions | join(', ') }}"
      include_tasks: version_item.yml
      with_items: "{{ postgresql_versions }}"
      loop_control:
        loop_var: postgresql_version
  become: true
  become_user: root
