---

- block:

    # Fedora 41: postgresql distro package replaces postgresql16 pgdg packages
    # postgresql Fedora packages do not provide expected .service systemd config
    # workaround: postgresql packages from fedora repos are ignored
    - name: "postgresql - ignore distro package"
      copy:
        dest: /etc/dnf/repos.override.d/postgresql-workaround.repo
        content: |
          [fedora]
          exclude=postgresql*

          [updates]
          exclude=postgresql*
      when: ansible_distribution == 'Fedora'
    
    - name: "postgresql - pgdg - drop pgdg {{ postgresql_clean_versions | join(', ') }}"
      include_tasks: pgdg_clean_repo_item.yml
      with_items: "{{ postgresql_clean_versions }}"
      loop_control:
        loop_var: postgresql_clean_version
      when: ansible_os_family == 'RedHat'

    - name: "postgresql - drop {{ postgresql_clean_versions | join(', ') }}"
      include_tasks: version_clean_item.yml
      with_items: "{{ postgresql_clean_versions }}"
      loop_control:
        loop_var: postgresql_clean_version
    
    - include_tasks: pgdg_check.yml
      with_items: "{{ postgresql_versions }}"
      loop_control:
        loop_var: pgdg_version
    
    - name: "postgresql - pgdg - install pgdg {{ postgresql_versions | join(', ') }}"
      include_tasks: pgdg_repo_item.yml
      with_items: "{{ postgresql_versions }}"
      loop_control:
        loop_var: pgdg_version
      when: ansible_os_family == 'RedHat'
    
    - import_tasks: pgdg_debian.yml
      when: ansible_os_family == 'Debian'
    
    - name: "postgresql - install {{ postgresql_versions | join(', ') }}"
      include_tasks: version_item.yml
      with_items: "{{ postgresql_versions }}"
      loop_control:
        loop_var: postgresql_version
  become: true
  become_user: root
