---

- name: "postgresql - {{ _postgresql_version }} - drop packages"
  package:
    name: "{{ postgresql_packages + postgresql_default_packages | distro(vars) }}"
    state: absent

  vars:
    _postgresql_version: "{{ postgresql_clean_version }}"
    _postgresql_version_stripped: "{{ postgresql_clean_version.replace('.', '') }}"
